# Generated by Django 2.0.6 on 2019-04-22 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=16, null=True, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('0', '女'), ('1', '男')], default='1', max_length=2, verbose_name='性别')),
                ('age', models.CharField(max_length=16, null=True, verbose_name='年龄')),
                ('major', models.CharField(max_length=64, null=True, verbose_name='专业')),
                ('department', models.CharField(max_length=64, null=True, verbose_name='系')),
                ('academy', models.CharField(max_length=64, null=True, verbose_name='院')),
                ('location', models.CharField(max_length=128, null=True, verbose_name='所在地')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生表',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=16, null=True, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('0', '女'), ('1', '男')], default='1', max_length=2, verbose_name='性别')),
                ('age', models.CharField(max_length=16, null=True, verbose_name='年龄')),
                ('department', models.CharField(max_length=64, null=True, verbose_name='系')),
                ('academy', models.CharField(max_length=64, null=True, verbose_name='院')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='团队名称')),
            ],
            options={
                'verbose_name': '团队',
                'verbose_name_plural': '团队表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, null=True, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=36, null=True, verbose_name='密码')),
                ('role', models.CharField(choices=[('1', '学生'), ('2', '老师')], default='1', max_length=2, verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.Team', verbose_name='团队'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.User', verbose_name='用户'),
        ),
    ]
