# Generated by Django 2.0.6 on 2019-04-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', '校长'), ('2', '老师'), ('3', '学生')], default='1', max_length=2, verbose_name='角色'),
        ),
    ]
